## Lists vs Np array

### Lets see time/performance

In [1]:
import numpy as np
import time

In [2]:
size = 1_000_0000

py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()


print(f"time taken by List = {end-start}")

np_arr = np.array(py_list)
start = time.time()
sq_arr = np_arr**2
end = time.time()


print(f"time taken by np Array = {end-start}")


time taken by List = 1.553055763244629
time taken by np Array = 0.046396732330322266


### lets see memory occupied

In [3]:
import sys
print(f"Size occupied by Python List = {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"Size occupied by np Array = {np_arr.nbytes} bytes")

Size occupied by Python List = 800000560000000 bytes
Size occupied by np Array = 80000000 bytes


## creating array using lists

In [4]:
arr1 = np.array([1,2,3,4,5]);
print(arr1,arr1.dtype,arr1.shape)

arr2 = np.array([1,2,3,4,5,"prime"]);
print(arr2,arr2.dtype,arr2.shape)

arr_2d = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]);
print(arr_2d,arr_2d.dtype,arr_2d.shape)

# arr_2d = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4]]); # will give an error dimensions has to be same for each row
# print(arr_2d,arr_2d.dtype,arr_2d.shape)

[1 2 3 4 5] int64 (5,)
['1' '2' '3' '4' '5' 'prime'] <U21 (6,)
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]] int64 (3, 5)


## using built-in methods

In [5]:
arr1 = np.zeros((3,2))
print(arr1)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [6]:
arr1 = np.zeros((3,2),dtype="int64")
print(arr1)

[[0 0]
 [0 0]
 [0 0]]


In [7]:
arr1 = np.zeros((3,))#1d array
print(arr1)

[0. 0. 0.]


In [8]:
arr2 = np.ones((3,2))
print(arr2)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:
arr2 = np.ones((3,)) # 1D
print(arr2)

[1. 1. 1.]


In [10]:
arr2 = np.ones((3,2),dtype="int64")
print(arr2,arr2.shape)

[[1 1]
 [1 1]
 [1 1]] (3, 2)


In [11]:
arr3 = np.full((3,2),5)
print(arr3)

[[5 5]
 [5 5]
 [5 5]]


In [12]:
arr3 = np.full((3,),5) # dtype depends on val passed
print(arr3)

[5 5 5]


In [13]:
arr3 = np.full((3,2),5.2)
print(arr3,arr3.dtype)

[[5.2 5.2]
 [5.2 5.2]
 [5.2 5.2]] float64


In [14]:
arr4 = np.eye(4) #identity matrix
print(arr4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
arr4 = np.eye(4,dtype="int64") #identity matrix
print(arr4)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [16]:
arr5 = np.arange(0,12,2)
print(arr5)

[ 0  2  4  6  8 10]


In [17]:
arr5 = np.arange(0,12,2).reshape(2,3) # only if possible to split LCM(m,n) == length
print(arr5)

[[ 0  2  4]
 [ 6  8 10]]


In [18]:
arr6 = np.linspace(0,11,2)
print(arr6)

[ 0. 11.]


In [19]:
arr6 = np.linspace(0,11,10)
print(arr6)

[ 0.          1.22222222  2.44444444  3.66666667  4.88888889  6.11111111
  7.33333333  8.55555556  9.77777778 11.        ]


## array properties

In [20]:
arr = np.array([1,2,3,4,5])
print(arr.size)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

5
(5,)
1
int64


In [21]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.size)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr,float_arr.dtype)

9
(3, 3)
2
int64
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


## Important Operations on Arrays

### 1. reshape

In [22]:
arr = np.array([[1,2,3],[4,5,6]])

arr2 = arr.reshape((3,2))
arr3 = arr.flatten();

print(arr)
print(arr2)
print(arr3)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


### 2. Indexing

In [23]:
arr = np.array([1,2,3,4,5])
print(arr[1])

arr[3] = 10
print(arr)

arr = np.array([[1,2,3],[4,5,6]])
print(arr[0][2])

2
[ 1  2  3 10  5]
3


In [24]:
# fancy indexing
arr = np.array([1,2,3,4,5])
idx = [1,3,4]
print(arr[idx])# only those elements returned whose index is passed

[2 4 5]


In [25]:
#boolean indexing
arr = np.array([1,2,3,4,5])
print(arr[arr>3])
print(arr[arr%2==0])

[4 5]
[2 4]


### 3. Slicing

slicing in numpy array is similar to python lists but there is a big difference ij how internally slicing takes place

- py list slicing -> creates a new copy of elements/subarray
- np array creates a view of original array which still points to subarray/subsequence within orig array
  to verify just update one elements in both and notice the change

In [26]:
arr = np.array([1,2,3,4,5])

print(arr[1:3])#[start,end,step]
print(arr[:3])
print(arr[1:])
print(arr[::2]) # alternate

[2 3]
[1 2 3]
[2 3 4 5]
[1 3 5]


## Multi dimensional arrays and Axes

In [30]:
arr = np.array([[1,2,3],[4,5,6]])
print(np.sum(arr))
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))

21
[5 7 9]
[ 6 15]


In [28]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr[0:2,1:2]) # slicing

[[2]
 [5]]


In [31]:
arr3D = np.array([
    [[1, 2], [3, 4], [5, 6]],
    [[7, 8], [9, 10], [11, 12]]
])

print(arr3D, arr3D.shape)

# indexing
print(arr3D[1, 1, 0])

# slicing
arr3D[:, 0, :] = 99   # first row from both layers

print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


## Vectorization in NumPy

Vectorization means replacing Python loops with fast NumPy operations.

In [32]:
#without vectorization
a = [1, 2, 3, 4]
b = []

for x in a:
    b.append(x * 2)

print(b)

[2, 4, 6, 8]


In [33]:
# with vectorization (Numpy)

a = np.array([1, 2, 3, 4])
b = a * 2
print(b)


[2 4 6 8]


In [34]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y)      # element-wise addition
print(x ** 2)     # element-wise power
print(np.sin(x))  # vectorized sin()


[5 7 9]
[1 4 9]
[0.84147098 0.90929743 0.14112001]


## Broadcasting in NumPy

Broadcasting allows NumPy to operate on arrays with different shapes by automatically expanding dimensions when possible.

###  Broadcasting Rules (simple version)

Two arrays can be broadcast if for each dimension:

They are equal, OR

One of them is 1

NumPy then stretches the dimension with value 1 to match the other.

In [41]:
arr = np.array([1, 2, 3])
print(arr + 5)


[6 7 8]


In [42]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

print(A + b)

# A.shape = (2, 3)

# b.shape = (3,) → broadcast to (1, 3) → (2, 3)


[[11 22 33]
 [14 25 36]]


In [43]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[10],
              [20]])

print(A + b)


[[11 12 13]
 [24 25 26]]


## Vector Normalization

In [48]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
mean = np.mean(A)
std_dev= np.std(A);


normalized_arr = (A-mean)/std_dev
print(normalized_arr)

[[-1.46385011 -0.87831007 -0.29277002]
 [ 0.29277002  0.87831007  1.46385011]]


## Mathematical Functions (some mostly used)

In [49]:
arr = np.array([5, 10, 15, 20, 25])

# ---- Aggregation Functions ----  -->perform ops on all and give single result
print("sum:", arr.sum())          # total of all elements
print("prod:", arr.prod())        # product of all elements
print("min:", arr.min())          # smallest value
print("max:", arr.max())          # largest value
print("mean:", arr.mean())        # average
print("std:", arr.std())          # standard deviation
print("var:", arr.var())          # variance
print("median:", np.median(arr))  # middle value
print("argmin:", arr.argmin())    # index of min value
print("argmax:", arr.argmax())    # index of max value

sum: 75
prod: 375000
min: 5
max: 25
mean: 15.0
std: 7.0710678118654755
var: 50.0
median: 15.0
argmin: 0
argmax: 4


In [50]:
# Power Functions

arr = np.array([1, 4, 9, 16])

print("square:", np.square(arr))      # x²
print("sqrt:", np.sqrt(arr))          # √x
print("pow:", np.power(arr, 3))       # x³
print("pow with 2 args:", np.power(2, 5))  # 2⁵

square: [  1  16  81 256]
sqrt: [1. 2. 3. 4.]
pow: [   1   64  729 4096]
pow with 2 args: 32


In [51]:
# Rounding functions 
arr = np.array([1.2, 2.7, -3.8, 4.5])

print("round:", np.round(arr))   # nearest integer
print("floor:", np.floor(arr))   # always down
print("ceil:", np.ceil(arr))     # always up
print("trunc:", np.trunc(arr))   # remove decimal part


round: [ 1.  3. -4.  4.]
floor: [ 1.  2. -4.  4.]
ceil: [ 2.  3. -3.  5.]
trunc: [ 1.  2. -3.  4.]


In [54]:
# Log & Exponential
arr = np.array([1, 10, 100, 1000])

print("log (natural):", np.log(arr))     # ln(x)
print("log10:", np.log10(arr))           # base-10
print("log2:", np.log2(arr))  
arr = np.array([0, 1, 2, 3])# base-2
print("exp:", np.exp(arr))               # e^x

log (natural): [0.         2.30258509 4.60517019 6.90775528]
log10: [0. 1. 2. 3.]
log2: [0.         3.32192809 6.64385619 9.96578428]
exp: [ 1.          2.71828183  7.3890561  20.08553692]


In [53]:
print("unique:", np.unique(arr))   # remove duplicates
print("sort:", np.sort(arr))       # ascending order
print("abs:", np.abs([-3, 0, 7]))  # absolute value

unique: [   1   10  100 1000]
sort: [   1   10  100 1000]
abs: [3 0 7]
